---

# -----------------------------------------------------------------------------
# setup apt sources
# -----------------------------------------------------------------------------

- name: set apt sources
  register: apt_source
  template: src=apt/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root

- name: update apt
  action: apt update_cache=yes
  when: apt_source|changed

# -----------------------------------------------------------------------------
# set best scheduler
# -----------------------------------------------------------------------------

- stat: path=/etc/default/grub
  register: grub_config

- name: set io scheduler
  lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=' line='GRUB_CMDLINE_LINUX="elevator={{jessie_server_base_scheduler}}"' state=present backrefs=yes
  notify:
    - update-grub
  when: grub_config.stat.exists == True


# -----------------------------------------------------------------------------
# secure ssh, https://pthree.org/2015/01/12/reasonable-ssh-security-for-openssh-6-0-or-later/
# -----------------------------------------------------------------------------

- lineinfile: "dest=/etc/ssh/sshd_config regexp='^Ciphers ' line='Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'"
- lineinfile: "dest=/etc/ssh/sshd_config regexp='^KexAlgorithms ' line='KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'"
- lineinfile: "dest=/etc/ssh/sshd_config regexp='^MACs ' line='MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com'"


- name: install security measures and services
  apt: pkg={{item}} state=installed
  with_items:
    - unattended-upgrades
    - ntp

# -----------------------------------------------------------------------------
# install common tools
# -----------------------------------------------------------------------------

- name: install tools
  apt: pkg={{item}} state=installed
  with_items:
    - htop
    - ne
    - iptraf
    - sysstat
    - rsync
    - iperf
    - hdparm
    - dnsutils
    - screen
    - acl
    - tree
